name: $(Build.BuildID)

pool:
  vmImage: "ubuntu-20.04"

steps:
  - task: qetza.replacetokens.replacetokens-task.replacetokens@3
    displayName: 'Replace tokens'
    inputs:
      targetFiles: |
        **/*.token.yml => *.yml

  - task: UseDotNet@2
    inputs:
      packageType: 'sdk'
      version: '5.0.x'

  - task: DotNetCoreCLI@2
    displayName: 'restore'
    inputs:
      command: 'restore'
      feedsToUse: 'select'

  - task: DotNetCoreCLI@2
    displayName: 'build'
    inputs:
      command: 'build'

  - task: DotNetCoreCLI@2
    displayName: 'unit tests'
    inputs:
      command: 'test'
      projects: '**/*Tests.csproj'

  - task: Docker@2
    displayName: Docker build
    condition: eq(variables['Build.Reason'], 'IndividualCI')
    inputs:
      command: build
      containerRegistry: 'official-docker-modmoto'
      repository: 'modmoto/battle-mate'
      arguments: --build-arg APP_VERSION=$(Build.BuildID)
      tags: |
        $(Build.BuildID),
        latest

  - task: Docker@2
    displayName: Docker push
    condition: eq(variables['Build.Reason'], 'IndividualCI')
    inputs:
      command: push
      containerRegistry: 'official-docker-modmoto'
      repository: 'modmoto/battle-mate'
      tags: |
        $(Build.BuildID),
        latest

  - task: CopyFiles@2
    displayName: publish docker-compose files
    inputs:
      contents: '**/*docker-compose.yml'
      targetFolder: $(Build.ArtifactStagingDirectory)

  - task: PublishBuildArtifacts@1
    inputs:
      pathToPublish: $(Build.ArtifactStagingDirectory)