version: '3.9'
services:
  battle-mate:
    image: modmoto/battle-mate:${TAG}
    container_name: battle-mate-${CONTAINER_SUFFIX}
    restart: unless-stopped
    expose:
      - 80

networks:
  default:
    external:
      name: caddy